### ISSUE TITLE
Examples please...

### ISSUE THREAD

**Issue by jdriesen** [shooterRao/vue-cli-plugin-svg-sprite-loader#1]
Hi @shooterRao ,

First of all, THANK YOU for sharing this component.
It's exactly what I'm looking for.

Though, I've a "custom" (sprites) SVG file, and I can't make it work...
(to be more precise, I don't know which settings I've to fill in in the **vue.config.js**)

So, can I kindly ask you to make a small example project, with some filled-in custom parameters in vue.config.js ?
(like ```dir: path.resolve(__dirname, "src/icon"),``` and ```symbolId: "icon-[name]"```)

PS.: I don't understand the Chinese language, which makes it a little bit hard to understand your readme.md file :)

Thanks in advance for your effort and reply.

Kind regards,
Johnny Driesen
Belgium.

**Comment by shooterRao** [comment]
Hi @jdriesen，


Thank you very much for using vue-plugin-svg-sprite-loader 😀


Regarding your question, I want to answer this for you


After using vue add svg-sprite-loader, vue.config.js usually does not need to be configured, unless your svg file is not in the `src / svg` folder, and your matching svg file rules need to be customized, And need to add some svg-sprite-loader configuration ...


So,I provided an example, you can refer to https://github.com/shooterRao/vue-cli-plugin-svg-sprite-loader-example


I hope that can help you!


shooterRao

**Comment by jdriesen** [comment]
Hi @shooterRao ,

Thanks for your feedback.
All clear now & all my probs are solved :)

Feel free to close this issue.

Kind regards,

Johnny Driesen
Belgium
